# Generated by Django 3.0 on 2019-12-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhavcopy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Stocks',
        ),
    ]
